### ISSUE TITLE
Invariant violation on React Native

### ISSUE THREAD

**Issue by joebernard** [boringdesigners/boring-avatars#10]
Awesome project! Does this work with React Native? I tried installing it but get this error when calling `Avatar`:

> Invariant Violation: View config getter callback for component `rect` must be a function (received `undefined`). Make sure to start component names with a capital letter.

I'm using the example code.

```Javascript
import Avatar from "boring-avatars";

<Avatar
  size={40}
  name="Maria Mitchell"
  variant="marble"
  colors={["#92A1C6", "#146A7C", "#F0AB3D", "#C271B4", "#C20D90"]}
/>;
```

```
"react": "17.0.1",
"react-native": "0.64.1",
```

**Comment by kacgrzes** [comment]
It does not. I'll try to propose some implementation tomorrow 😄

**Comment by RohovDmytro** [comment]
@kacgrzes , hi! Any news?

**Comment by kacgrzes** [comment]
Hello, I'm sorry, but I didn't have time to implement it. 😞 but I'll try to propose something this week 😄

**Comment by VirenMohindra** [comment]
Hey, any update on this? Is react-native support part of the road map? Thanks.

**Comment by mayank-budhiraja** [comment]
Hello! Please, let me know if I can propose an implementation for the same. Thanks

**Comment by luhart** [comment]
@joebernard @kacgrzes @RohovDmytro @VirenMohindra @mayank-budhiraja 

Hi everyone, I've made a react native library for boring-avatars. You can check it out [here](https://github.com/luhart/react-native-boring-avatars). Enjoy😄

**Comment by joebernard** [comment]
@luhart This is great! Thanks for putting in the effort. I am wondering what your thoughts are on migrating your changes into this repo so there is only one to maintain. Is that possible or do you plan to keep the fork?

**Comment by josepmartins** [comment]
Hi everyone 👋 , theres is no plan to make the library work on react-native. We recommend using other implementations, like the one @luhart made 👍 .
