### ISSUE TITLE
Vue.js port of boring-avatars

### ISSUE THREAD

**Issue by mujahidfa** [boringdesigners/boring-avatars#11]
First of all, really impressed with your work here! 

Since I am mainly a Vue user, I decided to make a Vue port called [vue-boring-avatars](https://github.com/mujahidfa/vue-boring-avatars). It uses a similar API with the same props, so you should be at home right away. Happy to discuss merging the Vue version to this repo if that is more desirable.

**Comment by KnowsCount** [comment]
yes, a vue version would be perfect.

**Comment by kacgrzes** [comment]
how about reorganizing this repo to a monorepo and add all the popular libraries implementation?

```sh
# this is where all the common js logic responsible for creating those patterns could live:
boring-avatars/shared

# different implementations
boring-avatars/react
boring-avatars/react-native
boring-avatars/vue
boring-avatars/svelte
# etc...

# and then in one project:
npm i boring-avatars/react boring-avatars/react-native

# and in the other:
npm i boring-avatars/angular
```

WDYT?

**Comment by leemcd56** [comment]
Maybe a rewrite in Stencil.js to generate framework-agnostic Web Components? It's integrates well with Angular, React, and Vue and is written by the Ionic team.

**Comment by kacgrzes** [comment]
I've never used `Stencil.js` before. Will it work with at least most popular frameworks? Also, react-native is a different renderer, so we'd need to create a separate package anyway.

**Comment by krhoyt** [comment]
@leemcd56 I work for Ionic (maintainers of Stencil) and am working on a port - should be done today. Once the monorepo PR has been accepted, I will place it in its own folder. 

@kacgrzes 
The output of a Stencil project is/can be standard web components. This means Stencil integrates with frameworks inasmuch as frameworks support web components. Framework integration steps are covered in the [documentation](https://stenciljs.com/docs/overview).

**Comment by KnowsCount** [comment]
I am currently working on the `vue2` version, written in javascript.
