### ISSUE TITLE
Two lockfiles

### ISSUE THREAD

**Issue by abhijit-hota** [boringdesigners/boring-avatars#13]
I see both `package-lock.json` and `yarn.lock` in the repo. The latter was last updated 5 months ago so I assume that's redundant now? Consider removing one.

P.S. Are lockfiles really needed for a library?

**Comment by josepmartins** [comment]
Closing this as I just removed the yarn.lock file https://github.com/boringdesigners/boring-avatars/commit/e03f1b9ba0ebac725936d34d8b378a1402f8d385.

Thank for the heads up @haneenmahd and @abhijit-hota
