### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN

### ISSUE THREAD

**Issue by QuentinGallard** [boringdesigners/boring-avatars#16]
Hi, it seems there is a SSL_ERROR_BAD_CERT_DOMAIN on https://boringavatars.com/

And even if I try to bypass the error, I can't open the page.

Do you have any hosting or certification problem ?

**Comment by KnowsCount** [comment]
hmm.. it lgtm.

**Comment by QuentinGallard** [comment]
I'm using Firefox 89.0 (64 bits), and Chrome Version 91.0.4472.77 (Build officiel) (64 bits), both on Ubuntu.

On the second one, I have a NET::ERR_CERT_COMMON_NAME_INVALID error.

By the way, I am behind a proxy and if I remove it, I can access without any problems.
So I think there is a conflict with my company vpn.

I think this ticket can be closed.
Thank you for your help.
Nice avatars, specially the beam ones !

**Comment by josepmartins** [comment]
Thank you @QuentinGallard
