### ISSUE TITLE
Is there an open api?

### ISSUE THREAD

**Issue by kitanin90** [boringdesigners/boring-avatars#22]
Is there an open api where you can send a request and get a random picture with a smile from the "beam" section?

**Comment by josepmartins** [comment]
Hi @kitanin90 👋, yes, we recently released a service where you can get a random SVG avatar via HTTP. You'll find more in the [README](https://github.com/hihayk/boring-avatars-service/blob/main/README.md). 

For your case and to request random `beam` variants: https://source.boringavatars.com/beam

Hope this helps.

**Comment by kitanin90** [comment]
Thanks!

**Comment by calin1611** [comment]
Any chance of providing the functionality of this service so that I can generate the avatars by myself in my own code without making an external request? I want to generate an avatar and save the png on the server so that it is persisted.
