### ISSUE TITLE
Feature request: option to display avatar with 2 letters over the background

### ISSUE THREAD

**Issue by Aarbel** [boringdesigners/boring-avatars#27]
Do you plan to bring a preview with letters overlaying the gradient background ? 

![image](https://user-images.githubusercontent.com/25119847/125489702-044aa57e-1187-4f6f-b99c-5986de1501e3.png)

**Comment by josepmartins** [comment]
Hey @Aarbel, no plans for making this happen, as there are lots of libraries that does that already. Our idea was to create something different away from that concept.

**Comment by Aarbel** [comment]
Fair, simply the other libraries are too "basic"
