### ISSUE TITLE
Question: how to help you to add more svg patterns ? 

### ISSUE THREAD

**Issue by Aarbel** [boringdesigners/boring-avatars#28]
Beautifull abstract avatars with custom color codes would be a great aesthetical alternative for the web, compared to ugly gravatars. Having a good pattern diversity would be wonderfull

# How to help you to add more patterns ? 

## Dribbble is full of examples:

![image](https://user-images.githubusercontent.com/25119847/125488738-9e7f6b23-b24e-45e4-aa14-b2fcbb646123.png)
![image](https://user-images.githubusercontent.com/25119847/125995254-d44cd9db-cc04-45f6-a184-e41790fdcf26.png)

![image](https://user-images.githubusercontent.com/25119847/125488771-4388e566-2c51-4d96-953f-8fd02c9edf67.png)
![image](https://user-images.githubusercontent.com/25119847/125488796-4856b8f1-77eb-4a4b-8a94-b3e48a50eb82.png)
![image](https://user-images.githubusercontent.com/25119847/125489413-90f9060f-5ae0-42d3-a0cb-6c739f6ea373.png)
![image](https://user-images.githubusercontent.com/25119847/125488636-9cbd8fb6-80cf-419e-8fb8-09e2e4853bc6.png)
![image](https://user-images.githubusercontent.com/25119847/125995293-11e08369-588c-4701-a57b-a59775df7a8c.png)
![image](https://user-images.githubusercontent.com/25119847/125995402-21d9ed39-f692-4cef-8739-872a84e06e39.png)
![image](https://user-images.githubusercontent.com/25119847/125995435-bffefd46-73d3-4913-bdd8-53c27b556992.png)
![image](https://user-images.githubusercontent.com/25119847/125995462-2a7ebc3d-1fd9-4e94-b9f4-c4d1ca24a128.png)

## Patternpad could be a good inspiration

https://patternpad.com/editor.html

![image](https://user-images.githubusercontent.com/25119847/125629045-7bbf7cf9-8f14-4ec7-a0d0-8573123ea79c.png)

**Comment by Aarbel** [comment]
@josepmartins so can we contribute to the patterns ?

Maybe we can if you validate the patterns graphism ? (so it fits your graphism quality requirements)

**Comment by Aarbel** [comment]
@josepmartins ? last up

**Comment by josepmartins** [comment]
Hey @Aarbel, sorry but at the moment we want to keep the library simple and we won't include more variants.

Thanks for your time

**Comment by Aarbel** [comment]
@josepmartins oh crap, so someone should create an other generative placeholders library...

The designer of this one was ready to open source it for boring avatars :
![image](https://user-images.githubusercontent.com/25119847/127062171-660e55de-91c7-432a-a1b1-cd1c97a8b25d.png)

Can your position evolve in a near future ? Or to you really want to keep it as a full personal brand lib ?
