### ISSUE TITLE
Doc request: length of colors array

### ISSUE THREAD

**Issue by Aarbel** [boringdesigners/boring-avatars#29]
![image](https://user-images.githubusercontent.com/25119847/125627196-b2ab176c-85be-4363-a2ed-3b5e78ef53e4.png)

What is the minimum / maximum length required for the array of colors ?

**Comment by josepmartins** [comment]
Hey @Aarbel so far, there is no mi/max length required, but depending on the variant, the `bauhaus` one for instance, we recommend using more than 4 colors.

**Comment by Aarbel** [comment]
👍
