### ISSUE TITLE
[Feature Request] We'll like to see in the future that this library supports React-Native. 

### ISSUE THREAD

**Issue by shamxeed** [boringdesigners/boring-avatars#30]
This is an awesome library but is there any plan to make it work with React-native?

Thanks for the hard work !!!

**Comment by luhart** [comment]
I've made a react-native port :) Check it out [here](https://github.com/luhart/react-native-boring-avatars).

**Comment by shamxeed** [comment]
@luhart Thanks, Man! Already gave it a star and gonna check it out tonight :)))

**Comment by luhart** [comment]
@shamxeed Let me know if you run into any issues😅

**Comment by lsharples1** [comment]
@luhart thanks for making this- just saved me a ton of time! works great

**Comment by baryon** [comment]
forked and upgraded to RN 0.74 and RNSVG   ^15.2.0
https://github.com/baryon/react-native-boring-avatars
