### ISSUE TITLE
Add links to community supported implementations

### ISSUE THREAD

**Issue by luhart** [boringdesigners/boring-avatars#36]
I think it would be helpful to have links to all the community supported implementations of boring-avatars in the readme.

The ports I'm aware of:

- [Vue](https://github.com/mujahidfa/vue-boring-avatars)
- [Laravel Blade](https://github.com/khaled-sadek/blade-boring-avatars)
- [React Native](https://github.com/luhart/react-native-boring-avatars)

Reply to this issue with any other implementations that exist :)

**Comment by mujahidfa** [comment]
Found a couple more:

- [Svelte](https://github.com/paolotiu/svelte-boring-avatars)
- [Vue 2](https://github.com/stonega/vue2-boring-avatars)
- [Angular](https://github.com/MitchellCash/ng-boring-avatars)
