### ISSUE TITLE
Question: Get a png format instead

### ISSUE THREAD

**Issue by ZiyadF296** [boringdesigners/boring-avatars#39]
Hey!
First off, thank you for this amazing library! 😍

It would be useful if I could possibly somehow get the avatar as a png/jpeg. Or if this is already possible, how can I do it?

**Comment by quentincaffeino** [comment]
@ZiyadF296 this should work https://www.gloomycorner.com/svg-to-png/ if you can get access to svg html element.

**Comment by ZiyadF296** [comment]
Hmm... I was mostly looking for an out-of-the-box solution.
