### ISSUE TITLE
Square avatars

### ISSUE THREAD

**Issue by root-io** [boringdesigners/boring-avatars#4]
Hey nice work! Would be amazing to have square avatars.

**Comment by abhijit-hota** [comment]
+1. Maybe a `borderRadius` prop behaving like the actual CSS `border-radius` to some extent, or taking strings like `none`, `sm`, `md` or `full`.

Also, amazing concept! =) Thanks for the lib.

**Comment by josepmartins** [comment]
We are working on this for our next release, thank you all for your time and patience ✨

**Comment by josepmartins** [comment]
We made some changes to expose an `square` prop on the library, more info here https://github.com/boringdesigners/boring-avatars/pull/24.

Thanks you all for your time! 🥳
