### ISSUE TITLE
Colors do not match

### ISSUE THREAD

**Issue by uguareschi** [boringdesigners/boring-avatars#46]
**Describe the bug**
I'm using the five colors that the component asks, but they show another color that I didn't put.

**To Reproduce**
On the Avatar component write the five colors that the component ask and see if it shows exactly that five colors. 

**Expected behavior**
Show just the colors that I introduce

**Screenshots**
<img width="101" alt="Screenshot 2022-03-24 at 20 06 30" src="https://user-images.githubusercontent.com/21092021/160029461-7277f044-9174-4457-83ad-d6a3c42f9639.png">

<img width="509" alt="Screenshot 2022-03-24 at 20 06 40" src="https://user-images.githubusercontent.com/21092021/160029478-3ee0c579-e895-411f-b9d0-a7d22b6a8937.png">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Brave

**Comment by muhammadsr** [comment]
Why does purple always show as a color?
