### ISSUE TITLE
Various SVG size values are not properly set

### ISSUE THREAD

**Issue by marcfrankel** [boringdesigners/boring-avatars#47]
**Describe the bug**
Several of the size values used within the generated SVG images are hardcoded and not based on the passed in size prop. This causes the size of the avatar to not always be respected and can lead to it being rendered blurry.

**To Reproduce**
Step 1: go to https://source.boringavatars.com/marble/120/Maria%20Mitchell?colors=264653,2a9d8f,e9c46a,f4a261,e76f51
Step 2: View source on the page
Step 3: Notice how the width and height (SIZE) in various places ("Viewbox", "mask", and "rect" for instance) are not 120, but instead are hardcoded to 80

**Expected behavior**
The user-supplied height is properly applied to the full svg

**Screenshots**

**Note:**
I tried manually editing a saved version of the image and setting all the properties to 120 and it works totally fine.

**Comment by josepmartins** [comment]
Hey @marcfrankel, that's right, I'll take a look as soon as I can. Thanks for raising this up

**Comment by marcfrankel** [comment]
Is there any update on this? I would love to use these in our project. But sadly the images appear very blurry without this change
