### ISSUE TITLE
How to ensure that the avatars are gender neutral?

### ISSUE THREAD

**Issue by tamilvendhank-helptap** [boringdesigners/boring-avatars#54]
**Is your feature request related to a problem? Please describe.**
This is a question than a feature request. 
I am unable to find any information related to making this gender neutral. 

**Describe the solution you'd like**
If there is an option to specify gender, like male, female, neutral, it would do.

**Comment by rachit1601** [comment]
All avatars are gender neutral, however if you find some avatars more inclined towards a gender, it could be mainly because of the colors, you can specify gender neutral colors if you want.

**Comment by tamilvendhank-helptap** [comment]
@rachit1601, okay, thanks.
