### ISSUE TITLE
Random avatars

### ISSUE THREAD

**Issue by jmaicaaan** [boringdesigners/boring-avatars#6]
Do we support the ability to get a random avatar per variant?

The use case would be to use this on a loop where each item doesn't have an avatar yet

Probably the API would be something like

```
<Avatar
  size={40}
  variant="marble"
  colors={["#92A1C6", "#146A7C", "#F0AB3D", "#C271B4", "#C20D90"]}
/>
```

When no `name` passed it will pick any of the avatar from the marble collection

**Comment by abhijit-hota** [comment]
> it will pick any of the avatar from the marble collection

I don't think it's a "collection" from where one can pick up Avatars. It's a variant, an input-output system. Regarding your use case, if you're looping through an array of objects or anything that has some value, you can always pass any string to it from the object's properties. 

If you're looping without an array, you can do the following:

```js
<Avatar
  size={40}
  name={Math.random().toString()}
  variant="marble"
  colors={["#92A1C6", "#146A7C", "#F0AB3D", "#C271B4", "#C20D90"]}
/>
```

**Comment by jmaicaaan** [comment]
Wow sounds good! We can now close this one 👍  Thanks 🎉
