### ISSUE TITLE
Framework-agnostic usage without React

### ISSUE THREAD

**Issue by khromov** [boringdesigners/boring-avatars#60]
**Is your feature request related to a problem? Please describe.**
Currently I can't use this excellent package without React.

**Describe the solution you'd like**

Something like this:

```ts
import { generateAvatar } from 'boring-avatars';

const avatar: string = generateAvatar({ size: 40, name: 'Maria Mitchell' /* Other supported settings, same as props */ });
```

So `generateAvatar` would just return the raw HTML string that could then be used in any JS framework.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by promatik** [comment]
One more for Vanilla JS 🙌
I would love to use this package, but I'm on vanilla team 🤷‍♂️
