### ISSUE TITLE
Add support for initials

### ISSUE THREAD

**Issue by alipas** [boringdesigners/boring-avatars#63]
### Context
There's no way to generate initials on top of avatars without custom solutions. 

This pertains particularly to the marble type unlike the other, visually busier, types.

### Proposed solution
An `initials` prop that takes a boolean or formatting function. If nothing else specified then use the name to generate initials. It would also be nice to be able to define the min or max amount of initials to display.

### Alternatives
Other libraries that support initials or custom solutions.

**Comment by josepmartins** [comment]
Hey @alipas, thanks for bringing this up. We built the library as an alternative to other libraries that uses initials, and we don't plan to add them anytime soon. I hope you understand 🙏
