### ISSUE TITLE
Restricts Avatar Variations due to Same Mask Use

### ISSUE THREAD

**Issue by totegamma** [boringdesigners/boring-avatars#64]
**Describe the bug**
When rendering several amounts of avatars, each avatar has its mask with the id "mask__beam"(when using avatar-beams.js).
But this is "ID," so the avatar's lookups are the first.
With this, we can't use circle and square avatars on the same page. And also, when specifying 'visibility: hidden' to the first one, the others go to hidden too.

**To Reproduce**
1. Go to https://codesandbox.io/s/inspiring-benz-rg5y6f?file=/src/App.js
2. I coded two avatars. One is a circle, and the other one is a square. But it rendered both squares.

**Expected behavior**
It should be square and circle.

Each avatar would have a random id or use border-radius instead.

**Screenshots**
![image](https://github.com/boringdesigners/boring-avatars/assets/7270849/3424da36-220c-482a-9dff-625e6bc6de76)
↑second one should be square
![image](https://github.com/boringdesigners/boring-avatars/assets/7270849/20b100ca-a375-4838-88c4-de1aa4684553)
↑ second one should be visible

**Desktop:**
 - OS: Windows10
 - Browser GoogleChrome
 - Version 114.0.5735.91

**Additional context**
ref: https://www.antonball.dev/blog/2020-06-15-svg-id-collision/

Thanks for developing this library! I love 'beam' cute avatars.

**Comment by totegamma** [comment]
I fixed this with the way to use random maskID.
https://github.com/boringdesigners/boring-avatars/compare/master...totegamma:boring-avatars:master?expand=1
I will make this as a PR if you like it.

**Comment by josepmartins** [comment]
hey @totegamma thanks for dropping this. We had other PR's attempting to fix this issue in the past. 

I believe the best solution would be to use the `useId` hook instead of `uuid` library. I'll create a PR and release a fix this same week 👍

**Comment by josepmartins** [comment]
The latest release `1.8.0` should fix the issue. @totegamma let me know if that works. Thanks for you work again!
