### ISSUE TITLE
v1.8.0 missing JS bundle

### ISSUE THREAD

**Issue by smonn** [boringdesigners/boring-avatars#67]
**Describe the bug**
I just happened to be upgrading our dependencies and noticed that the just released v1.8.0 is missing the JS files. Downgrading to v1.7.0 works.

**To Reproduce**
1. Install v1.8.0
2. Check `node_modules/boring-avatars/`
3. Observe that there are no JS files (`build/index.js` is missing)

**Expected behavior**
The JS should be included in the release artifacts.

**Comment by josepmartins** [comment]
Hey @smonn this should be fixed with the latest `1.10` version 🙏
