### ISSUE TITLE
500: INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by mrleblanc101** [boringdesigners/boring-avatars#68]
https://source.boringavatars.com/beam/126/S%C3%A9bastien%20LeBlanc?colors=22131d,682959,7e326c,985b89,e0d4dd&square
![Capture d’écran, le 2023-06-13 à 15 32 16](https://github.com/boringdesigners/boring-avatars/assets/17392251/8511c812-4008-4ec3-93ed-74d83456590e)

**Comment by josepmartins** [comment]
Hey @mrleblanc101 not getting any 500 🤔 is that still happening?

**Comment by mrleblanc101** [comment]
It seems to have fixed itself 🤷‍♂️

**Comment by josepmartins** [comment]
I've looked at the logs as well, couldn't find any 500 response 🤷‍♂️ 

Closing this for now 👍
