### ISSUE TITLE
Export to png and set dimensions for it

### ISSUE THREAD

**Issue by heitoke** [boringdesigners/boring-avatars#69]
I would like to be able to get the result not only in SVG, but also in PNG format. Since, for example, when zooming on the site, and if you scroll the page, the SVG picture will slow down a little.

**Comment by josepmartins** [comment]
Hey @heitoke, unfortunately we don't consider supporting PNG at the moment, as this project was meant to provide SVG assets only. Thank you and I hope you understand 🙏 .

**Comment by heitoke** [comment]
It's a pity, I wanted to be able to :D Ok thank you
