### ISSUE TITLE
Get avatar via URL

### ISSUE THREAD

**Issue by jmaicaaan** [boringdesigners/boring-avatars#7]
Would it be possible to have this on a hosting site where we can get an avatar via URL like how the following URLs are doing?

https://placeholder.com/
https://placekitten.com/
https://placedog.net/

**Comment by abhijit-hota** [comment]
This would be really interesting!

@jmaicaaan If you're looking for an alternative now, you can try this: https://github.com/tobiaslins/avatar

**Comment by gpng** [comment]
Found this idea interesting so attempted to make my own, at https://hostedboringavatars.vercel.app
The code is quite simple, can be found here https://github.com/gpng/hosted-boring-avatars

If the maintainers of boringavatars are planning to make their, I can take down this site if requested

**Comment by alexmarles** [comment]
This feature request looks more suitable for [boringdesigners/boring-avatars-playground](https://github.com/boringdesigners/boring-avatars-playground), which is the playground website the authors set up.

**Comment by josepmartins** [comment]
Hi there 👋. We just released a new service to embed Boring Avatars via URL 🎉

To generate an avatar just embed the following URL https://source.boringavatars.com/.  Now you can append the variant, size and the username to generate an avatar to get the SVG.

You'll find more information on the service [README](https://github.com/hihayk/boring-avatars-service/blob/main/README.md).

Thank you all for your time  🙏🥲

**Comment by jmaicaaan** [comment]
Awesome! Appreciate to all people involved on this discussion and this project 🎉

**Comment by ex3ndr** [comment]
Are there any sources for source.boringavatar.com?
