### ISSUE TITLE
Same url generate different image

### ISSUE THREAD

**Issue by thibault60000** [boringdesigners/boring-avatars#72]
**Describe the bug**
Same url generate different image

**To Reproduce**
ex : https://source.boringavatars.com/marble/80/?colors=a7c5bd,e5ddcb,eb7b59,cf4647,524656 
and spam F5 to refresh page, image with same url are different

How to fix this image (for example to save the string on database for a nice user avatar)

Thanks ! :)

**Comment by josepmartins** [comment]
Hey @thibault60000! The url example is missing the name of the user, otherwise it generates a random example every time.

Check the docs of the service here: https://github.com/boringdesigners/boring-avatars-service/
