### ISSUE TITLE
Add a "avatar" category tag to the github project

### ISSUE THREAD

**Issue by kbooz** [boringdesigners/boring-avatars#73]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a "avatar" tag on the github project

**Additional context**
I've tried to find an avatar service/component to use on my project, and this lib didn't appeared for me while searching for "avatar" category on github

(:

**Comment by josepmartins** [comment]
good point @kbooz thanks for the suggestion 🙏 ! I've already added some `avatar` related tags to the repo description 🥳 

<img width="774" alt="Screenshot 2023-09-04 at 08 06 33" src="https://github.com/boringdesigners/boring-avatars/assets/912236/92a17da6-6e24-4a91-a99e-23f2ec73691f">
