### ISSUE TITLE
TypeError: n.useId is not a function

### ISSUE THREAD

**Issue by Zahnstochermann** [boringdesigners/boring-avatars#74]
**Describe the bug**
Page crashes with the error: "TypeError: n.useId is not a function"

**To Reproduce**
1) install boring-avatars via npm
2) use basic example from readme in a react component

**Expected behavior**
No error.

**Screenshots**
![image](https://github.com/boringdesigners/boring-avatars/assets/4338707/d110384e-c95d-46d1-90b2-77511dbf612e)

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome (v 120)
- React 17.0.2

**Comment by robbieredfearn-dpm** [comment]
Having the same issue here. Took me days to figure out why my app was breaking 😆 Thanks for flagging this! Will use a different plugin 💨
