### ISSUE TITLE
`Element type is invalid` error in latest Remix.run project

### ISSUE THREAD

**Issue by kishanhitk** [boringdesigners/boring-avatars#76]
**Describe the bug**
The `Avatar` component is not working in latest Remix.run project. Getting this error

**To Reproduce**
1. Create a new Remix app
2. Install the library
3. Add the default `Avatar` component.

**Expected behavior**
It should render the avatar

**Screenshots**
![image](https://github.com/boringdesigners/boring-avatars/assets/41117038/a6c50c86-4cd5-4cf6-9387-2e12def4fbaf)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Arc
 - Version Latest

**Additional context**
I even tried making the component client side only, and skipping the render of it during SSR, still getting the issue.

**Comment by macklinu** [comment]
I ran into the same issue, so I opened https://github.com/boringdesigners/boring-avatars/pull/78 as a potential solution.

**Comment by macklinu** [comment]
Not stale

**Comment by jtanguy** [comment]
I have managed to make the import work without re-bundling this library. I added a check to use the default export

```jsx
import Boring from "boring-avatars";

const RealBoring = typeof Boring.default !== "undefined" ? Boring.default : Boring
// Then use RealBoring as you would use Boring
```
