### ISSUE TITLE
Smooth deprecation suggestion

### ISSUE THREAD

**Issue by alexeysarakuz** [boringdesigners/boring-avatars#79]
Just noticed on the readme that you are planning to deprecate the library, if so, please try to smoothly/gracefully deprecate it by relying on the alternative solution -> `https://www.dicebear.com/playground/`

The integration looks pretty similar:

`<img
  src="https://api.dicebear.com/9.x/thumbs/svg?seed=Princess"
  alt="avatar" />`

Also their "thumbs" theme looks similar to the boringavatars. 

It should be pretty quick to migrate, but users of this library will avoid seeing 404.

Hope it helps!

**Comment by josepmartins** [comment]
Hey @alexeysarakuz, thanks for the suggestion. The problem here is the amount of daily requests through the service.  

To avoid this we created a new subscription service plan to cover expenses. More info here: https://boringdesigners.gumroad.com/l/boring-avatars-service
