### ISSUE TITLE
I subscribed to the service and never got my endpoint. Email to contact boringavatars is dead ... the link goes to "gmail.com"

### ISSUE THREAD

**Issue by rrluthi** [boringdesigners/boring-avatars#80]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by josepmartins** [comment]
Hey @rrluthi, can you send me an email to jsp.mrtns@gmail.com with the domains and your Gumroad order id?
