### ISSUE TITLE
Add support for `className` and `style` props

### ISSUE THREAD

**Issue by jahirfiquitiva** [boringdesigners/boring-avatars#81]
**Is your feature request related to a problem? Please describe.**

I am unable to style the resulting SVG using CSS classes or styles

**Describe the solution you'd like**

Add support for `className` and `style` props

**Describe alternatives you've considered**

Wrapping the component into another one, which is not ideal (for me)

**Comment by mcle0463** [comment]
all we would need to do is set the height and width of the svg to 100%. actually im not sure why this isnt an option already. We could just pass a prop like "responsive: true". I suspect that because the paid api allows you to embed the src directly in an img element, which allows you to style it however you want, this was intentionally left out of the npm package.

best thing to do is create a pr with the feature.

**Comment by josepmartins** [comment]
> element

Hey, believe it or not, there's nothing intentional about leaving className props or style, or even the responsive behaviour out of the npm vs the paid API 😅. It's been like this since the beginning and till now noone has requested such feature, which I agree the npm package should provide.

**Comment by mcle0463** [comment]
I believe you it just hasnt been my experience in the past. I created a hasty pr for this feature..take what you will from that https://github.com/boringdesigners/boring-avatars/pull/82

**Comment by josepmartins** [comment]
@jahirfiquitiva I just pushed some changes spreading missing props to the rest of components. You can check them here https://github.com/boringdesigners/boring-avatars/commit/223ddbec4d9b851ef7c0213bb2aac73d42402157

In latest v1.11.0 you should be able to use `style`, `className` or any extra property. Thank you!

**Comment by mcle0463** [comment]
i think the typescript exports will need to be updated

**Comment by josepmartins** [comment]
@mcle0463 @TheOrdinaryWow I just released a patch v1.11.1 that fixes the typescript exports and fixes the latest warnings 👍
