### ISSUE TITLE
How to use it in vanilla HTML and Javascript?

### ISSUE THREAD

**Issue by elgs** [boringdesigners/boring-avatars#9]
How to use it in vanilla HTML and Javascript?

**Comment by quentincaffeino** [comment]
This would require some work but I would also like to see this as a framework-independent solution with a possibility to use with react out of the box.

**Comment by krhoyt** [comment]
I've started a port to web components. I have marble, beam, and pixels completed at this point. They can be used as individual components, and there is also a wrapper component that allows toggling between the variations. I can put in a PR when I get the other three variants completed. It'll be up to the maintainer(s) from there.

**Comment by kacgrzes** [comment]
@krhoyt How about [this idea](https://github.com/boringdesigners/boring-avatars/issues/11#issuecomment-851592480)?

**Comment by krhoyt** [comment]
Yes, this works for me.

**Comment by doctafaustus** [comment]
If anyone would like to make an official PR this feel free. I just wanted the "Beam" style avatars so I pulled that code out, hardcoded a few things, and translated it to vanilla here:
https://stackblitz.com/edit/js-6dtnda

**Comment by hustcc** [comment]
Vanilla JavaScript version: https://github.com/hustcc/boring-avatars-vanilla

**Comment by elgs** [comment]
Still what if I don’t want to depend on npm?

**Comment by hustcc** [comment]
> Still what if I don’t want to depend on npm?

Use umd cdn: https://unpkg.com/boring-avatars-vanilla/dist/index.umd.js or jsdelivr, see the [readme](https://github.com/hustcc/boring-avatars-vanilla).
